# -*- coding: utf-8 -*-
"""Colab_Walmart_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESuuFOMPWcM8JtrHjHaJlCfGb1_ZEHPb
"""

# استيراد المكتبات
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
!pip install seaborn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

from prophet import Prophet

df = pd.read_csv("/content/Walmart.csv")

df.head()

df.shape

df.info()

df.isna().sum()

df=df.sort_values('Date')
df['Date']

df.describe()

#Plot histograms of weel;y sales
plt.figure(figsize=(10,5))
plt.hist(df['Weekly_Sales'], bins=40)
plt.title("Distribution of Weekly Sales")
plt.xlabel("Weekly Sales")
plt.ylabel("Frequency")
plt.show()

#boxplot of weekly sales
#Outliers
plt.figure(figsize=(8,5))
plt.boxplot(df['Weekly_Sales'], vert=False)
plt.title("Boxplot of Weekly Sales")
plt.xlabel("Weekly Sales")
plt.show()

#density plot of weekly
plt.figure(figsize=(10,5))
df['Weekly_Sales'].plot(kind='density')
plt.title("Density Plot of Weekly Sales")
plt.xlabel("Weekly Sales")
plt.show()

plt.figure(figsize=(10,5))

# Histogram
plt.hist(df['Weekly_Sales'], bins=40, density=True, alpha=0.5)

# Density curve
df['Weekly_Sales'].plot(kind='density')

plt.title("Weekly Sales Distribution with Density Curve")
plt.xlabel("Weekly Sales")
plt.ylabel("Density")
plt.show()

numeric_df = df.select_dtypes(include=['number'])
corr = numeric_df.corr()
corr

plt.figure(figsize=(12,8))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

# تحويل التاريخ من يوم-شهر-سنة إلى datetime
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

# تجهيز بيانات Prophet
df_tsf = df[['Date', 'Weekly_Sales']].copy()
df_tsf = df_tsf.rename(columns={'Date':'ds', 'Weekly_Sales':'y'})

df_tsf = df_tsf.sort_values('ds')

df_tsf = df_tsf.sort_values('ds')

import warnings
warnings.filterwarnings('ignore') # Suppress specific warnings from Prophet

# Reinstall prophet with pystan (often resolves backend issues)
!pip install --upgrade prophet pystan

from prophet import Prophet

# Re-run the model initialization and fitting

model = Prophet()
model.fit(df_tsf)

future = model.make_future_dataframe(periods=52, freq='W')

forecast = model.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

model.plot(forecast)
plt.title("Weekly Sales Forecast")
plt.xlabel("Date")
plt.ylabel("Weekly Sales")
plt.show()

model.plot_components(forecast)
plt.show()